version: '3.1'

services:

  zip:
    build: .
    command:
      - zip -r ship.zip ship -x "ship/.git/*" "ship/.idea/*"
      - mv ship.zip ship/ship-$$(cat-version ship/Dockerfile).zip
    volumes:
      - ./:/app/ship

  fail:
    build: .
    command:
      - expr 1 / 0
      - echo "asdasd"
    volumes:
      - ./:/app/ship
